### ISSUE TITLE
Optimize CI/CD runs

### ISSUE THREAD

**Issue by Doreapp** [Doreapp/skillect#20]
## What ?

Limit the duration of CI/CD execution and there occurrences. It means running a CI/CD job only when it is necessary. For example check the linting of the python scripts only when a python script was updated.

## Why ?

In order to fasten CI/CD executions and reduce the overall computing time. Indeed, even it the CI/CD runs are done in github magic cloud, it still is physically executed on computers. Thus, doing less CI/CD runs will reduce the power consumption of these devices, and so the CO2 emissions (even if most likely negligible regarding other emissions). 

## How ?

- [ ] Separate the jobs in several workflows, such as one dedicated to the frontend (with Typescript linter) and one for the backend (with Python linter, unit and integration tests)
- [ ] Add triggers to run the job only on some files push (see below)

--------
:bulb: Run workflow only on files push

```yaml
# .github/workflow-for-python.yml
on:
  push:
    paths:
      - "backend/app/**"
      - "backend/requirements*"
      - "**.py"
# ...
```
